//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_facility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllogreport
    {
        public int logid { get; set; }
        public string LogDescription { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> LogCapturedTime { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> partNo { get; set; }
        public Nullable<int> operationNo { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> userId { get; set; }
        public string programNumber { get; set; }
        public int IsDeleted { get; set; }
        public string LogInfo { get; set; }
    }
}
